### ISSUE TITLE
Modificar datos mostrados de un agente al hacer login web

### ISSUE THREAD

**Issue by ameliafb** [Arquisoft/Agents_e3a#11]
Cuando un agente se logea vía web están apareciendo datos: dirección, nacionalidad, apellidos.
Hay que modificarlo para que sólo aparezca:
- nombre (nombre y apellidos en caso de una persona)
- localización (coordenadas gps, si no tiene sale en blanco)
- email
- id
- kind
- kindCode

**Comment by PelayoDiaz** [comment]
Completado y con tests pasando.
