### ISSUE TITLE
Pruebas con Curl o Advanced REST client

### ISSUE THREAD

**Issue by FJss23** [Arquisoft/Agents_e3a#2]
Realizar las pruebas necesarias utilizando alguna de las herramientas como curl o la extension de navegador Advanced REST client.
- Curl: https://curl.haxx.se/
- Advanced REST client: https://chrome.google.com/webstore/detail/advanced-rest-client/hgmloofddffdnphfgcellkdfbfbjeloo

**Comment by ameliafb** [comment]
Probado y funcionando.
