### ISSUE TITLE
Documentación 1º entregable

### ISSUE THREAD

**Issue by FJss23** [Arquisoft/Agents_e3a#5]
Hay que actualizar la documentación para el primer entregable. Aquí se señalarán los cambios añadidos a al documento.

**Comment by ameliafb** [comment]
De la parte que nos toca (Agents) actualizados todos los puntos (7 y 8 está @FJss23 con ellos); me falta incluir los diagramas.
Dejo marcadas en amarillo las partes a modificar por la otra parte del equipo (Loader).

**Comment by ameliafb** [comment]
Listos los dos diagramas pendientes; dejo en la carpeta de oneDrive los ficheros de los diagramas por si hay que editarlos, o el otro equipo (Loader) los necesita.

**Comment by FJss23** [comment]
Añadidos los diagramas de los apartados 7 y 8

**Comment by FJss23** [comment]
Acabados los apartados 7 y 8 de la documentación

**Comment by ameliafb** [comment]
Repaso gral. de todo el documento, hay párrafos marcados en rosa que habría que comentar (x dudas) @FJss23 .
De la parte de Loader hay aún cosas sin modificar (pto. 9), les aviso por WhatsApp. Tampoco veo referencia al fichero maestro en csv

**Comment by ameliafb** [comment]
Entregada documentación el 19/02/2018. Se sube también a GitHub en carpeta doc
